version: 0.0
os: linux
files:
  - source: /fastapi
    destination: /Apps/fastapi/
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user

