version: 0.2

phases:
  pre_build:
    commands:
      - echo build
  build:
    commands:
      - echo build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
    
reports:
  coverage:
    files:
      - "coverage/*"
    base-directory: 'test-reports'
    discard-paths: yes
  report:
    files:
      - 'junit.xml'
      - 'report.html'
      - 'assets/*'
    base-directory: 'test-reports'
    discard-paths: yes
    file-format: JunitXml