version: 0.2

env:
  secrets-manager:
    LOGIN: sonarcloud:sonartoken
    HOST: sonarcloud:HOST
    Organization: sonarcloud:Organization
    Project: sonarcloud:Project

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y jq
      - apt-get -y install maven
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.2.1.4610-linux-x64.zip
      - unzip ./sonar-scanner-cli-6.2.1.4610-linux-x64.zip
      - export PATH=$PATH:/sonar-scanner-cli-6.2.1.4610-linux-x64/bin/
  build:
    commands:
      - echo mvn sonar:sonar -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.organization=$Organization
      - sonar-scanner -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.organization=$Organization
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project >result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi