version: 0.2

phases:
  pre_build:
    commands:
      - echo pre-build
  build:
    commands:
      - echo build
      - pip install --no-cache-dir -r requirements.txt
      - python setup.py sdist bdist_wheel
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'