version: 0.2

phases:
  pre_build:
    commands:
      - echo pre-build
  build:
    commands:
      - echo build
      - pip install --no-cache-dir -r requirements.txt
      - pytest 
        --html=test-reports/report.html 
        --self-contained-html
        -s
        -v
        --cov=dspt 
        --cov-report=html:test-reports/coverage 
        --junitxml=test-reports/junit.xml 
        --log-file=test-reports/logs.txt 
        test/test.py
  post_build:
    commands:
      - echo Test completed on `date`
    
reports:
  coverage:
    files:
      - "coverage/*"
    base-directory: 'test-reports'
    discard-paths: yes
  report:
    files:
      - 'junit.xml'
      - 'report.html'
      - 'assets/*'
    base-directory: 'test-reports'
    discard-paths: yes
    file-format: JunitXml